version: '3.1'

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080