# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: alex
      MONGO_INITDB_ROOT_PASSWORD: harvest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: alex
      ME_CONFIG_MONGODB_ADMINPASSWORD: harvest
      ME_CONFIG_MONGODB_URL: mongodb://alex:harvest@mongo:27017/